name: Tests

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.cache/pip
                      ~/.platformio/.cache
                  key: ${{ runner.os }}-pio
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.9"
            - name: Install PlatformIO Core
              run: pip install --upgrade platformio
            - name: Setup env variables
              run: make setup-env
            - name: Run native tests
              run: make test-native
            - name: Build default
              run: platformio run
